### PR TITLE
Addition of filtering of XML output

### PR DESCRIPTION
**Pull request by Mesuva**
This adds an extra option on the dashboard page to filter output XML to only selected nodes.

The default list of nodes are ones I believe are relevant for when you are creating starting points for themes. 

I thought this would be useful as opposed to having to manually edit the XML after output each time.

### CODE REVIEW

**Comment by krebbi** [comment]
works like a charme. 
could somebody please merge this PR?

**Comment by aembler** [comment]
I'll merge this, but know that this addon isn't actively being developed any longer. It has been replaced by the much more full-featured Content Export portion of the Migration Tool
https://github.com/concrete5/addon_migration_tool

**Comment by Mesuva** [comment]
I don't know if the new tool even existed when I submitted this PR!

This one still might be handy to have around, but yep, it's understood it's no longer being developed.

**Comment by aembler** [comment]
@Mesuva yep, should have merged it at the time, totally just fell through the cracks until the recent comment on it.

**Pull request merged**
